import { Component, OnInit } from '@angular/core';
import { MessageService } from 'primeng/api';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.css'],
  providers: [MessageService],
})
export class CardComponent implements OnInit {
  constructor(private messageService: MessageService) {}

  upcoming_data: Object[] = [
    {
      event_type: 'upcoming',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
    {
      event_type: 'upcoming',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
    {
      event_type: 'upcoming',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
    {
      event_type: 'upcoming',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
    {
      event_type: 'upcoming',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
    {
      event_type: 'upcoming',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
  ];

  live_data: Object[] = [
    {
      event_type: 'live',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
    {
      event_type: 'live',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
    {
      event_type: 'live',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
    {
      event_type: 'live',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
    {
      event_type: 'live',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
    {
      event_type: 'live',
      tag1: 'Full Time',
      tag2: 'Hourly',
      tag3: 'Part Time',
      status: 'In Progress ...',
      job_title: 'Software Engeneer',
      posted: '5 Days Ago',
      count: '25',
      company: 'American Express',
      package: '20 LPA',
      job_type: 'Part Time',
      location: 'Hyderabad',
    },
  ];

  onTabChange(event) {
    this.messageService.add({
      severity: 'info',
      summary: 'Tab Expanded',
      detail: 'Index: ' + event.index,
    });
  }
  ngOnInit(): void {}
}
